version: "3.8"

services:
  fava:
    container_name: fava
    build:
      context: ./fava
    volumes:
      - ./fava:/fava/
    ports:
      - 5000:5000
    command: ["/fava/ledger.beancount"]
    restart: unless-stopped

  home-assistant:
    container_name: home-assistant
    init: true
    image: homeassistant/home-assistant:stable
    environment:
      TZ: "Europe/Rome"
    volumes:
      - ./home-assistant:/config
    ports:
      - 8123:8123
    restart: unless-stopped

  code-server:
    image: ghcr.io/linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./code-config:/config
      - /home:/home
    ports:
      - 8443:8443
    restart: unless-stopped
